CREATE TABLE `facility_submissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`address` varchar(500) NOT NULL,
	`city` varchar(100) NOT NULL,
	`state` varchar(100) NOT NULL,
	`zipCode` varchar(20),
	`phone` varchar(50),
	`email` varchar(320),
	`website` varchar(500),
	`category` varchar(100) NOT NULL,
	`materialsAccepted` text,
	`additionalNotes` text,
	`submitterName` varchar(255),
	`submitterEmail` varchar(320),
	`status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
	`reviewNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `facility_submissions_id` PRIMARY KEY(`id`)
);
