CREATE TABLE `facilities` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`address` varchar(500) NOT NULL,
	`state` varchar(100) NOT NULL,
	`county` varchar(100),
	`phone` varchar(100),
	`email` varchar(320),
	`website` varchar(500),
	`category` varchar(150) NOT NULL,
	`facilityType` varchar(150),
	`feedstock` text,
	`naicsCode` varchar(20),
	`latitude` varchar(30),
	`longitude` varchar(30),
	`hours` varchar(500),
	`acceptsDropoff` varchar(50),
	`feeStructure` varchar(50),
	`feeDetails` text,
	`offersPayment` varchar(50),
	`paymentDetails` text,
	`source` varchar(50) NOT NULL DEFAULT 'csv_import',
	`submissionId` int,
	`isActive` int NOT NULL DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `facilities_id` PRIMARY KEY(`id`)
);
